# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4199432cf99b2dc6e6fed2817751037a389c82545ef52563b0c2d5e40098728b9baea9bc7325e3e15a275d8b7cf723b3bb222fa356c0ba65cfaa9cda771d692e

test:
  secret_key_base: 1afcf429b713bba45a4dca0d42ff2f3a4e91875e2babca76f35de8c8944b4f79ec8352b489464c96cb327a87f515f3b52e7456a9502046e370ff5ca9ce1a995b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
